export const TFT_WORK = {
	title: 'TFT Decision Support Tool',
	images: [
		'/img/dst/home.png',
		'/img/dst/login.png',
		'/img/dst/table.png',
		'/img/dst/program.png',
		'/img/dst/plot.png',
		'/img/dst/map1.png',
		'/img/dst/map2.png',
		'/img/dst/map3.png',
	],
	technologies: [
		'Google Cloud',
		'Docker',
		'PostgreSQL',
		'Typescript',
		'Oauth',
		'React',
		'Express',
		'Mapbox',
		'Material-UI',
	],
	description: `In this project, I developed a full-stack application that leverages ML data sources to help guide the decision-making of River Restoration investments. The application uses a Javascript API and React Frontend deployed to Goggle Cloud as Docker containers.`,
}
